name: "RC522 Reader"
description: "Reads RC522 via SPI and publishes UID to MQTT"
version: "0.2.1"
slug: "rc522_reader"
init: false
startup: services
arch:
  - aarch64

devices:
  - /dev/spidev0.0
  - /dev/spidev0.1
  - /dev/spidev1.0
  - /dev/spidev1.1

options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  topic_base: "rfid/rc522"
  spi_bus: 0
  spi_device: 0
  poll_ms: 200
  removed_ms: 800

schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str?
  mqtt_password: password?
  topic_base: str
  spi_bus: "int(0,1)"
  spi_device: "int(0,2)"
  poll_ms: "int(50,2000)"
  removed_ms: "int(100,5000)"
